name: Controlled Deployment with Approval Timer

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        type: choice
        options:
          - dev
          - stg
          - perf
          - ppe
          - promote-prod
          - prod
      ref:
        description: 'Branch or Tag'
        required: true
        default: 'main'

jobs:
  control-deployment:
    runs-on: ubuntu-latest
    outputs:
      stages: ${{ steps.set-stages.outputs.stages }}
    steps:
      - name: Determine deployment sequence
        id: set-stages
        run: |
          case "${{ inputs.environment }}" in
            dev)   echo "stages=[\"dev\",\"stg\",\"perf\",\"ppe\",\"promote-prod\",\"prod\"]" >> $GITHUB_OUTPUT ;;
            stg)   echo "stages=[\"stg\",\"perf\",\"ppe\",\"promote-prod\",\"prod\"]" >> $GITHUB_OUTPUT ;;
            perf)  echo "stages=[\"perf\",\"ppe\",\"promote-prod\",\"prod\"]" >> $GITHUB_OUTPUT ;;
            ppe)   echo "stages=[\"ppe\",\"promote-prod\",\"prod\"]" >> $GITHUB_OUTPUT ;;
            promote-prod) echo "stages=[\"promote-prod\",\"prod\"]" >> $GITHUB_OUTPUT ;;
            prod)  echo "stages=[\"prod\"]" >> $GITHUB_OUTPUT ;;
          esac

  deploy-stages:
    needs: control-deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: ${{ fromJson(needs.control-deployment.outputs.stages) }}
    environment: 
      name: ${{ matrix.stage }}
      url: "https://${{ matrix.stage }}.example.com"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Wait for approval (1 minute)
        id: approval
        run: |
          echo "Waiting for approval... You have 1 minute to approve."
          timeout 60s bash -c "until [ -f approved.flag ]; do sleep 1; done"
        
      - name: Check if approval was made
        id: check-approval
        run: |
          if [ ! -f approved.flag ]; then
            echo "Approval timed out!"
            exit 1
          fi

      - name: Deploy to ${{ matrix.stage }}
        if: matrix.stage != 'promote-prod' && steps.check-approval.outcome == 'success'
        run: ./scripts/deploy.sh ${{ matrix.stage }}

      - name: Promote artifacts
        if: matrix.stage == 'promote-prod' && steps.check-approval.outcome == 'success'
        run: ./scripts/promote.sh

      - name: Set skip status
        if: ${{ matrix.stage != 'prod' }}
        run: echo "SKIP_NEXT=${{ github.event.inputs.skip_next || 'no' }}" >> $GITHUB_ENV

    continue-on-error: ${{ needs.deploy-stages.outputs.skip_next == 'false' }}
