name: Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        type: choice
        options:
          - dev
          - stg
          - perf
          - ppe
          - promote-prod
          - prod
      ref:
        description: 'Branch or Tag'
        required: true
        default: 'main'
      next_stage:
        description: 'Action after this stage'
        required: true
        type: choice
        options:
          - continue
          - skip
          - stop

jobs:
  deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      ref: ${{ github.event.inputs.ref }}
      next_stage: ${{ github.event.inputs.next_stage }}
