name: Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        type: choice
        options:
          - dev
          - stg
          - perf
          - ppe
          - promote-prod
          - prod
      ref:
        description: 'Branch or Tag'
        required: true
        default: 'main'
      skip_next_stage:
        description: 'Skip next stage? (yes/no)'
        required: false
        default: 'no'

jobs:
  dev:
    if: ${{ github.event.inputs.environment == 'dev' }}
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: dev
      ref: ${{ github.event.inputs.ref }}
    outputs:
      skip_next: ${{ steps.skip-check.outputs.skip_next }}

  stg:
    if: ${{ github.event.inputs.environment == 'stg' || (needs.dev.result == 'success' && needs.dev.outputs.skip_next != 'yes') }}
    needs: [dev]
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: stg
      ref: ${{ github.event.inputs.ref }}
    outputs:
      skip_next: ${{ steps.skip-check.outputs.skip_next }}

  perf:
    if: ${{ github.event.inputs.environment == 'perf' || (needs.stg.result == 'success' && needs.stg.outputs.skip_next != 'yes') }}
    needs: [stg]
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: perf
      ref: ${{ github.event.inputs.ref }}
    outputs:
      skip_next: ${{ steps.skip-check.outputs.skip_next }}

  ppe:
    if: ${{ github.event.inputs.environment == 'ppe' || (needs.perf.result == 'success' && needs.perf.outputs.skip_next != 'yes') }}
    needs: [perf]
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: ppe
      ref: ${{ github.event.inputs.ref }}
    outputs:
      skip_next: ${{ steps.skip-check.outputs.skip_next }}

  promote-prod:
    if: ${{ github.event.inputs.environment == 'promote-prod' || (needs.ppe.result == 'success' && needs.ppe.outputs.skip_next != 'yes') }}
    needs: [ppe]
    uses: ./.github/workflows/promote-prod.yml
    with:
      ref: ${{ github.event.inputs.ref }}
    outputs:
      skip_next: ${{ steps.skip-check.outputs.skip_next }}

  prod:
    if: ${{ github.event.inputs.environment == 'prod' || (needs.promote-prod.result == 'success' && needs.promote-prod.outputs.skip_next != 'yes') }}
    needs: [promote-prod]
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: prod
      ref: ${{ github.event.inputs.ref }}
