name: Non-Prod Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        type: choice
        options:
          - dev
          - stg
          - perf
          - ppe
          - promote-prod
      ref:
        description: 'Branch or Tag'
        required: true
        default: 'main'

jobs:
  dev:
    if: ${{ github.event.inputs.environment == 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Dev
        uses: ./.github/workflows/deploy-reusable1.yml
        with:
          environment: dev
          ref: ${{ github.event.inputs.ref }}

  stg:
    if: ${{ github.event.inputs.environment == 'stg' || needs.dev.result == 'success' }}
    needs: [dev]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Staging
        uses: ./.github/workflows/deploy-reusable1.yml
        with:
          environment: stg
          ref: ${{ github.event.inputs.ref }}

  perf:
    if: ${{ github.event.inputs.environment == 'perf' || needs.stg.result == 'success' }}
    needs: [stg]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Performance
        uses: ./.github/workflows/deploy-reusable1.yml
        with:
          environment: perf
          ref: ${{ github.event.inputs.ref }}

  ppe:
    if: ${{ github.event.inputs.environment == 'ppe' || needs.perf.result == 'success' }}
    needs: [perf]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Pre-Prod
        uses: ./.github/workflows/deploy-reusable1.yml
        with:
          environment: ppe
          ref: ${{ github.event.inputs.ref }}

  promote-prod:
    if: ${{ github.event.inputs.environment == 'promote-prod' || needs.ppe.result == 'success' }}
    needs: [ppe]
    runs-on: ubuntu-latest
    steps:
      - name: Promote Artifacts to Prod
        uses: ./.github/workflows/promote-prod.yml
        with:
          ref: ${{ github.event.inputs.ref }}
