name: Promote Artifacts to Nexus

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Promote Artifacts to Nexus
        run: ./scripts/promote.sh

      - name: Ask for Approval for Production Deployment
        run: echo "Promotion complete. Approve Production deployment."
