name: Promote Artifacts to Nexus

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
    outputs:
      skip_next:
        description: "Indicates if the next stage should be skipped"
        value: ${{ jobs.promote.outputs.skip_next }}

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Promote Artifacts to Nexus
        run: |
          echo "Promoting artifacts to Nexus..."
          ./scripts/promote.sh

      - name: Set Skip Next Stage Variable
        id: skip-check
        run: |
          if [ "${{ github.event.inputs.skip_next_stage }}" == "yes" ]; then
            echo "skip_next=yes" >> $GITHUB_ENV
          else
            echo "skip_next=no" >> $GITHUB_ENV
          fi
