name: Reusable Approval Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  approval:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}  # This enables manual approval in GitHub UI

    steps:
      - name: Wait for Manual Approval
        run: echo "Manual approval required for ${{ inputs.environment }}"

      - name: Deploy to ${{ inputs.environment }}
        run: echo "Deploying to ${{ inputs.environment }}"
