name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Choose the environment'
        required: true
        type: choice
        options:
          - dev
          - stg
          - perf
          - ppe
          - promote-prod
          - prod
      SERVICE:
        description: 'Select Service (Required only for Dev environment)'
        required: false
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Load Utility Scripts
        run: |
          echo "Environment: ${{ github.event.inputs.ENVIRONMENT }}"
          echo "Service: ${{ github.event.inputs.SERVICE }}"
  
  deploy:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [dev, stg, perf, ppe, promote-prod, prod]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Load Deployment Script
        run: |
          chmod +x scripts/deploy.sh
          scripts/deploy.sh ${{ matrix.stage }}

      - name: Execute Deployment for ${{ matrix.stage }}
        run: |
          echo "Deploying to ${{ matrix.stage }}"
          ./scripts/deploy.sh ${{ matrix.stage }}

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Post Deployment Success
        run: echo "Deployment completed successfully!"
